// DialogueNameGenerator.cs
// PELETAKAN: Assets/Scripts/Editor/DialogueNameGenerator.cs
// FUNGSI: Auto-generate DialoguesNames.cs dari DialogSequence assets
#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Linq;

public class DialogueNameGenerator : EditorWindow
{
    private const string OUTPUT_PATH = "Assets/Scripts/Generated/DialoguesNames.cs";
    private const string SEQUENCE_FOLDER = "Assets/ScriptableObjects/DialogSequence";
    
    [MenuItem("Tools/Generate Dialogue Names")]
    public static void GenerateDialogueNames()
    {
        // Find all DialogSequence assets
        string[] guids = AssetDatabase.FindAssets("t:DialogSequence", new[] { SEQUENCE_FOLDER });
        
        if (guids.Length == 0)
        {
            Debug.LogWarning("[DialogueNameGenerator] Tidak ada DialogSequence ditemukan di: " + SEQUENCE_FOLDER);
            return;
        }
        
        // Sort by name
        var sequences = guids
            .Select(guid => AssetDatabase.GUIDToAssetPath(guid))
            .Select(path => AssetDatabase.LoadAssetAtPath<DialogSequence>(path))
            .Where(seq => seq != null)
            .OrderBy(seq => seq.name)
            .ToList();
        
        // Generate code
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// Auto-generated file. Do not edit manually.");
        sb.AppendLine("// Generated by: Tools > Generate Dialogue Names");
        sb.AppendLine("public static class DialoguesNames");
        sb.AppendLine("{");
        
        foreach (var seq in sequences)
        {
            string constName = MakeValidConstName(seq.name);
            string assetName = seq.name;
            
            sb.AppendLine($"\tpublic const string {constName} = \"{assetName}\";");
        }
        
        sb.AppendLine("}");
        
        // Ensure directory exists
        string directory = Path.GetDirectoryName(OUTPUT_PATH);
        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }
        
        // Write file
        File.WriteAllText(OUTPUT_PATH, sb.ToString());
        AssetDatabase.Refresh();
        
        Debug.Log($"[DialogueNameGenerator] ✓ Generated {sequences.Count} dialogue names to: {OUTPUT_PATH}");
    }
    
    private static string MakeValidConstName(string input)
    {
        // Replace invalid characters with underscore
        StringBuilder sb = new StringBuilder();
        
        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
            else if (c == '-' || c == ' ' || c == '_')
            {
                sb.Append('_');
            }
        }
        
        string result = sb.ToString();
        
        // Ensure starts with letter or underscore
        if (char.IsDigit(result[0]))
        {
            result = "_" + result;
        }
        
        return result;
    }
    
    [MenuItem("Tools/Generate Dialogue Names", true)]
    private static bool ValidateGenerateDialogueNames()
    {
        // Enable menu item only if DialogSequence folder exists
        return AssetDatabase.IsValidFolder(SEQUENCE_FOLDER);
    }
}
#endif